### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by andreibarabas** [alikazemkhanloo/react-native-reanimated-slider#2]
Hi,

The gif you posted it seems really good, but I can't seem to make it work like that. We are still seeing lags.

Can you post an example on how to properly integrate this with react-native-video v5?

**Comment by andreibarabas** [comment]
My guess is the lagging is because we update the progress based on a callback from react-native-video's onProgress.

In your example, you use Animated.Value, so the value never reaches JS but remains in native, but can't seem to make it work with react-native-video.

**Comment by andreibarabas** [comment]
nor expo video

**Comment by alikazemkhanloo** [comment]
A working example can be found in [react-native-video-controller](https://github.com/alikazemkhanloo/react-native-video-controller).
`react-native-video` uses `react`'s `Animated.Value` without `useNativeDriver`. so it will reach JS thread.
in this library I used `react-native-reanimated`'s `Animated.Value`, so you have to do sth like this:

```js
<Video
  ...
  onProgress={({
    currentTime,
    playableDuration,
    seekableDuration
  }) => {
    this.setState({
      currentTime,
      seekableDuration,
    });
/>
```

and then convert the `currentTime` to `Animated.Value` from `react-native-reanimated` and pass it as props.
