### ISSUE TITLE
Can't find variable: Reanimated

### ISSUE THREAD

**Issue by shariqahmed49** [alikazemkhanloo/react-native-reanimated-slider#5]
Hello,

After installing the react-native-reanimated-slider and importing it to the screen is throwing a error 

Can't find variable: Reanimated

React Native version : 0.63.2

**Comment by hamswaldenkv** [comment]
Hello
`import Reanimated from 'react-native-reanimated';`
Just add this import

**Comment by alikazemkhanloo** [comment]
Thanks, I Updated the docs.
