### ISSUE TITLE
how to update position?

### ISSUE THREAD

**Issue by sonnysantino** [alikazemkhanloo/react-native-reanimated-slider#9]
I'm trying to update the `min`, `cache`, `progress` & `max` Animated.Value` values using `value.setValue()` but is not not working, any idea what i'm doing wrong? how it should be updated?

```jsx
const totalTime = new Value(100);
const currentTime = new Value(10);

// On a external update, currentTime.setValue(25)

<Slider 
    ...
    max={totalTime}
    progress={currentTime}
/>
```

Thanks :D

**Comment by sonnysantino** [comment]
Ok i've said nothing, i've make it work by putting the values inside a state

**Comment by hirbod** [comment]
I was about to ask the same. But it can't be right that a state update is required. That would kill the purpose of reanimated values at this point.

**Comment by sonnysantino** [comment]
@hirbod try this:


```js

import Animated, { Value } from "react-native-reanimated";

const [currentPos] = useState(new Value(0));

<ReSlider progress={currentPos} />

currentPos.setValue(100);
```

**Comment by hirbod** [comment]
I'll give it a try and report back, thanks!
